-- NETGUARD database schema (MySQL/MariaDB) - CONSOLIDATED VERSION
-- This is the ORIGINAL base schema. Safe to run once, first, in
-- phpMyAdmin's SQL tab, against a fresh database.
-- STATUS: ALREADY RUN LONG AGO on the original project machine.
-- Pulled verbatim from PROJECT_STATE_HANDOFF6.md section 4.3b.

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS traffic_samples;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;

CREATE DATABASE IF NOT EXISTS netguard;
USE netguard;

-- Accounts for login/registration. Passwords are NEVER stored in plain
-- text - password_hash holds a bcrypt hash, generated by the backend.
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin', 'viewer') NOT NULL DEFAULT 'viewer',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Real intrusion alerts from the sensor. Includes dest_ip and signature
-- (matches the class ER diagram) plus geolocation fields for source_ip -
-- geo_is_private stays TRUE for LAN/private addresses (192.168.x.x etc.)
-- since public geolocation APIs can't resolve those to a real place.
CREATE TABLE alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  source_ip VARCHAR(45) NOT NULL,
  dest_ip VARCHAR(45) NULL,
  event_type VARCHAR(50) NOT NULL,
  severity ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'medium',
  message TEXT,
  signature VARCHAR(150) NULL,
  mitre_id VARCHAR(20),
  mitre_name VARCHAR(100),
  geo_country VARCHAR(100) NULL,
  geo_city VARCHAR(100) NULL,
  geo_is_private BOOLEAN NOT NULL DEFAULT FALSE,
  acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
  acknowledged_by INT NULL,
  acknowledged_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (acknowledged_by) REFERENCES users(id)
);

-- Sampled "normal traffic" heartbeat lines for the Live Traffic Monitor
-- panel (separate from alerts, same as before).
CREATE TABLE traffic_samples (
  id INT AUTO_INCREMENT PRIMARY KEY,
  source_ip VARCHAR(45) NOT NULL,
  dst_port INT,
  bytes INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for common query patterns: newest-first ordering, filtering by
-- event type/severity.
CREATE INDEX idx_alerts_created_at ON alerts (created_at);
CREATE INDEX idx_alerts_event_type ON alerts (event_type);
CREATE INDEX idx_traffic_created_at ON traffic_samples (created_at);
